# Generated by Django 4.2.5 on 2023-09-24 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40)),
                ('topic_text', models.CharField(help_text='A topic or subtopic of study.', max_length=150)),
                ('modified', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('subtopic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizdata.topic', verbose_name='Subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('M', 'Multiple Choice'), ('B', 'Fill in the Blank')], default='M', max_length=1)),
                ('question_text', models.TextField(help_text='The question.')),
                ('is_suppressed', models.BooleanField()),
                ('force_ordered', models.BooleanField()),
                ('modified', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizdata.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40)),
                ('choice_text', models.CharField(max_length=150)),
                ('choice_order', models.IntegerField()),
                ('modified', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizdata.question')),
            ],
        ),
    ]
