# Generated by Django 4.2.5 on 2023-09-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=40),
        ),
    ]
