# Generated by Django 4.2.5 on 2023-09-29 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizdata", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionbucket",
            options={"ordering": ["-modified"]},
        ),
    ]
