# Generated by Django 4.2.5 on 2023-09-30 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizdata", "0002_alter_questionbucket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbucket",
            name="review_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="questionbucket",
            name="bucket",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)],
            ),
        ),
    ]
