# Generated by Django 4.2.5 on 2023-09-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdata', '0002_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
    ]
