# Generated by Django 4.2.5 on 2023-09-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizdata", "0003_questionbucket_review_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="topic_level",
            field=models.IntegerField(
                choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Advanced"), (4, "Expert"), (5, "Master")], default=1
            ),
        ),
    ]
