# Generated by Django 4.2.5 on 2023-09-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizdata', '0003_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizdata.topic'),
        ),
    ]
