# Generated by Django 4.2.5 on 2023-09-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdata', '0005_alter_choice_options_remove_choice_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='force_ordered',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_suppressed',
            field=models.BooleanField(null=True),
        ),
    ]
