# Generated by Django 4.2.5 on 2023-09-25 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdata', '0007_choice_is_correct_topic_topic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
