# Generated by Django 4.2.5 on 2023-09-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdata', '0010_topic_user_alter_topic_topic_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='topic',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
