# Generated by Django 4.2.5 on 2023-09-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizdata', '0011_rename_user_topic_owner_topic_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(help_text='A brief introduction to the topic.', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='The question.', max_length=300),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Hide from views'),
        ),
    ]
