# Generated by Django 4.2.5 on 2023-09-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizdata', '0014_alter_choice_options_alter_choiceanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceanswer',
            options={},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='choiceanswer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='question',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quizdata.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizdata.choice'),
        ),
        migrations.AddConstraint(
            model_name='choiceanswer',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'choice'), name='unique_user_question_choice'),
        ),
    ]
