# Generated by Django 4.2.5 on 2023-09-25 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DragQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('order', models.IntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paper.dragquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dragquestion',
            name='papers',
            field=models.ManyToManyField(through='paper.PaperQuestion', to='paper.paper'),
        ),
    ]
